LoadPlugin("D:\megui\tools\lsmash\LSMASHSource.dll")
LSMASHVideoSource("H:\Data\User\Raka Suryaardi Widjaja\Web\Confucius.ID\Video\Instrument\Dengan Semangat Nabi Khongcu Menyambut Tahun Baru\Dengan Semangat Nabi Khongcu Menyambut Tahun Baru.mp4")
#deinterlace
#crop
#resize
#denoise

LoadPlugin("D:\megui\tools\avisynth_plugin\VSFilter.dll")
TextSub("H:\Data\User\Raka Suryaardi Widjaja\Web\Confucius.ID\Video\Instrument\Dengan Semangat Nabi Khongcu Menyambut Tahun Baru\Dengan Semangat Nabi Khongcu Menyambut Tahun Baru Karaoke.ass", 1)
