LoadPlugin("D:\megui\tools\lsmash\LSMASHSource.dll")
LSMASHVideoSource("H:\Data\User\Raka Suryaardi Widjaja\Web\Confucius.ID\Video\Instrument\Jalan Yang Benar\Jalan Yang Benar.mp4")
#deinterlace
#crop
#resize
#denoise

LoadPlugin("D:\megui\tools\avisynth_plugin\VSFilter.dll")
TextSub("H:\Data\User\Raka Suryaardi Widjaja\Web\Confucius.ID\Video\Instrument\Jalan Yang Benar\Jalan Yang Benar Karaoke.ass", 1)
