LoadPlugin("D:\megui\tools\lsmash\LSMASHSource.dll")
LSMASHVideoSource("H:\Data\User\Raka Suryaardi Widjaja\Web\Confucius.ID\Video\Instrument\Sumber Air Nan Abadi\Sumber Air Nan Abadi.mp4")
#deinterlace
#crop
#resize
#denoise

LoadPlugin("D:\megui\tools\avisynth_plugin\VSFilter.dll")
TextSub("H:\Data\User\Raka Suryaardi Widjaja\Web\Confucius.ID\Video\Instrument\Sumber Air Nan Abadi\Sumber Air Nan Abadi Karaoke.ass", 1)
