LoadPlugin("D:\megui\tools\lsmash\LSMASHSource.dll")
LSMASHVideoSource("H:\Data\User\Raka Suryaardi Widjaja\Web\Confucius.ID\Video\Album\Genta Kebajikan 1998\Sadar Dan Berjanji\Sadar Dan Berjanji.mp4")
#deinterlace
#crop
#resize
#denoise

LoadPlugin("D:\megui\tools\avisynth_plugin\VSFilter.dll")
TextSub("H:\Data\User\Raka Suryaardi Widjaja\Web\Confucius.ID\Video\Album\Genta Kebajikan 1998\Sadar Dan Berjanji\Sadar Dan Berjanji Karaoke.ass", 1)
