LoadPlugin("D:\megui\tools\lsmash\LSMASHSource.dll")
LSMASHVideoSource("H:\Data\User\Raka Suryaardi Widjaja\Web\Confucius.ID\Video\Album\Genta Kebajikan 1998\Jangan Lupakan Dia\Jangan Lupakan Dia.mp4")
#deinterlace
#crop
#resize
#denoise

LoadPlugin("D:\megui\tools\avisynth_plugin\VSFilter.dll")
TextSub("H:\Data\User\Raka Suryaardi Widjaja\Web\Confucius.ID\Video\Album\Genta Kebajikan 1998\Jangan Lupakan Dia\Jangan Lupakan Dia Karaoke.ass", 1)
